/* Pinned RTGL1 ABI declarations; see RTGL1.h copyright notice. */
RT_EXPORT(RgResult, rgCreateInstance, (const RgInstanceCreateInfo *pInfo, RgInstance *pResult))
RT_EXPORT(RgResult, rgDestroyInstance, (RgInstance rgInstance))
RT_EXPORT(RgResult, rgUploadGeometry, (RgInstance rgInstance, const RgGeometryUploadInfo *pUploadInfo))
RT_EXPORT(RgResult, rgUpdateGeometryTransform, (RgInstance rgInstance, const RgUpdateTransformInfo *pUpdateInfo))
RT_EXPORT(RgResult, rgUpdateGeometryTexCoords, (RgInstance rgInstance, const RgUpdateTexCoordsInfo *pUpdateInfo))
RT_EXPORT(RgResult, rgBeginStaticGeometries, (RgInstance rgInstance))
RT_EXPORT(RgResult, rgSubmitStaticGeometries, (RgInstance rgInstance))
RT_EXPORT(RgResult, rgUploadRasterizedGeometry, (RgInstance rgInstance, const RgRasterizedGeometryUploadInfo *pUploadInfo, const float *pViewProjection, const RgViewport *pViewport))
RT_EXPORT(RgResult, rgUploadLensFlare, (RgInstance rgInstance, const RgLensFlareUploadInfo *pUploadInfo))
RT_EXPORT(RgResult, rgUploadDecal, (RgInstance rgInstance, const RgDecalUploadInfo *pUploadInfo))
RT_EXPORT(RgResult, rgUploadPortal, (RgInstance rgInstance, const RgPortalUploadInfo *pUploadInfo))
RT_EXPORT(RgResult, rgUploadDirectionalLight, (RgInstance rgInstance, const RgDirectionalLightUploadInfo *pUploadInfo))
RT_EXPORT(RgResult, rgUploadSphericalLight, (RgInstance rgInstance, const RgSphericalLightUploadInfo *pUploadInfo))
RT_EXPORT(RgResult, rgUploadSpotLight, (RgInstance rgInstance, const RgSpotLightUploadInfo *pUploadInfo))
RT_EXPORT(RgResult, rgUploadPolygonalLight, (RgInstance rgInstance, const RgPolygonalLightUploadInfo *pUploadInfo))
RT_EXPORT(RgResult, rgCreateMaterial, (RgInstance rgInstance, const RgMaterialCreateInfo *pCreateInfo, RgMaterial *pResult))
RT_EXPORT(RgResult, rgCreateAnimatedMaterial, (RgInstance rgInstance, const RgAnimatedMaterialCreateInfo *pCreateInfo, RgMaterial *pResult))
RT_EXPORT(RgResult, rgChangeAnimatedMaterialFrame, (RgInstance rgInstance, RgMaterial animatedMaterial, uint32_t frameIndex))
RT_EXPORT(RgResult, rgUpdateMaterialContents, (RgInstance rgInstance, const RgMaterialUpdateInfo *pUpdateInfo))
RT_EXPORT(RgResult, rgDestroyMaterial, (RgInstance rgInstance, RgMaterial material))
RT_EXPORT(RgResult, rgCreateCubemap, (RgInstance rgInstance, const RgCubemapCreateInfo *pCreateInfo, RgCubemap *pResult))
RT_EXPORT(RgResult, rgDestroyCubemap, (RgInstance rgInstance, RgCubemap cubemap))
RT_EXPORT(RgResult, rgStartFrame, (RgInstance rgInstance, const RgStartFrameInfo *pStartInfo))
RT_EXPORT(RgResult, rgDrawFrame, (RgInstance rgInstance, const RgDrawFrameInfo *pDrawInfo))
RT_EXPORT(RgBool32, rgIsRenderUpscaleTechniqueAvailable, (RgInstance rgInstance, RgRenderUpscaleTechnique technique))
RT_EXPORT(const char*, rgGetResultDescription, (RgResult result))
