/* Generated by Prepare-RTIntegration.py from pinned RTGL1 CreateDevice. */
#define RT_REQUIRED_BASE(X) \
 X(robustBufferAccess) \
 X(fullDrawIndexUint32) \
 X(imageCubeArray) \
 X(independentBlend) \
 X(logicOp) \
 X(multiDrawIndirect) \
 X(drawIndirectFirstInstance) \
 X(depthClamp) \
 X(depthBiasClamp) \
 X(depthBounds) \
 X(multiViewport) \
 X(samplerAnisotropy) \
 X(pipelineStatisticsQuery) \
 X(vertexPipelineStoresAndAtomics) \
 X(fragmentStoresAndAtomics) \
 X(shaderTessellationAndGeometryPointSize) \
 X(shaderImageGatherExtended) \
 X(shaderStorageImageExtendedFormats) \
 X(shaderStorageImageMultisample) \
 X(shaderStorageImageReadWithoutFormat) \
 X(shaderStorageImageWriteWithoutFormat) \
 X(shaderUniformBufferArrayDynamicIndexing) \
 X(shaderSampledImageArrayDynamicIndexing) \
 X(shaderStorageBufferArrayDynamicIndexing) \
 X(shaderStorageImageArrayDynamicIndexing) \
 X(shaderClipDistance) \
 X(shaderCullDistance) \
 X(shaderFloat64) \
 X(shaderInt64) \
 X(shaderInt16) \
 X(shaderResourceResidency) \
 X(shaderResourceMinLod) \
 X(inheritedQueries)
#define RT_REQUIRED_V12(X) \
 X(samplerMirrorClampToEdge) \
 X(runtimeDescriptorArray) \
 X(shaderSampledImageArrayNonUniformIndexing) \
 X(shaderStorageBufferArrayNonUniformIndexing) \
 X(bufferDeviceAddress) \
 X(shaderFloat16) \
 X(drawIndirectCount)
#define RT_REQUIRED_MULTIVIEW(X) \
 X(multiview)
#define RT_REQUIRED_STORAGE16(X) \
 X(storageBuffer16BitAccess)
#define RT_REQUIRED_SYNC2(X) \
 X(synchronization2)
#define RT_REQUIRED_PIPELINE(X) \
 X(rayTracingPipeline)
#define RT_REQUIRED_ACCELERATION(X) \
 X(accelerationStructure)
#define RT_REQUIRED_EXTENSIONS(X) \
 X(VK_KHR_SWAPCHAIN_EXTENSION_NAME) \
 X(VK_KHR_DEFERRED_HOST_OPERATIONS_EXTENSION_NAME) \
 X(VK_KHR_PIPELINE_LIBRARY_EXTENSION_NAME) \
 X(VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME) \
 X(VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME) \
 X(VK_KHR_SYNCHRONIZATION_2_EXTENSION_NAME) \
 X(VK_KHR_SHADER_FLOAT16_INT8_EXTENSION_NAME)
